import Nav from "@/{components}/Nav";
import scss from "../styles/_main.module.scss";
import Footer from "@/{components}/Footer";
import Header from "@/{components}/Header";

export const metadata = {
  title: "TopBuilderPicks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={scss.body}>
        <Nav />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
